name: testbuild

on:
  push:
    branches:
      - master

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        sudo apt update
        sudo apt install --yes lld
    - name: Build
      run: |
        mkdir _build && cd _build
        # XXX WORKAROUND: disable to build tools because of disk full.
        CC=clang CXX=clang++ LDFLAGS='-fuse-ld=lld' cmake \
          -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_DOCS=OFF \
          -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS='clang;lld' \
          -DLLVM_BUILD_TOOLS=OFF -G 'Unix Makefiles' ../llvm
        cmake --build . --parallel "$(nproc)"
    - name: Test
    - run: |
        cd ../t/regress
        make test
