name: testbuild

on:
  push:
    branches:
      - master

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir _build && cd _build
        CC=clang CXX=clang++ LDFLAGS='-fuse-ld=lld' cmake \
          -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_INCLUDE_DOCS=OFF -DLLVM_TARGETS_TO_BUILD=X86 \
          -DLLVM_ENABLE_PROJECTS='clang;lld' -G 'Unix Makefiles' ../llvm
        cmake --build . --parallel "$(nproc)"
